[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["googleapis", "busboy"]
timeout = 25

[[headers]]
for = "/*"
  [headers.values]
  Basic-Auth = "guest:b0d0129"
